using Sanford.Multimedia.Midi;

namespace MidiApp.MidiController.Controller
{
    /// <summary>
    /// Represents the different types of MIDI control changes based on ControllerType
    /// </summary>
    public enum ControlChangeType
    {
        None = -1,
        BankSelect = ControllerType.BankSelect,
        ModulationWheel = ControllerType.ModulationWheel,
        BreathControl = ControllerType.BreathControl,
        FootPedal = ControllerType.FootPedal,
        PortamentoTime = ControllerType.PortamentoTime,
        DataEntrySlider = ControllerType.DataEntrySlider,
        Volume = ControllerType.Volume,
        Balance = ControllerType.Balance,
        Pan = ControllerType.Pan,
        Expression = ControllerType.Expression,
        EffectControl1 = ControllerType.EffectControl1,
        EffectControl2 = ControllerType.EffectControl2,
        GeneralPurposeSlider1 = ControllerType.GeneralPurposeSlider1,
        GeneralPurposeSlider2 = ControllerType.GeneralPurposeSlider2,
        GeneralPurposeSlider3 = ControllerType.GeneralPurposeSlider3,
        GeneralPurposeSlider4 = ControllerType.GeneralPurposeSlider4,
        BankSelectFine = ControllerType.BankSelectFine,
        ModulationWheelFine = ControllerType.ModulationWheelFine,
        BreathControlFine = ControllerType.BreathControlFine,
        FootPedalFine = ControllerType.FootPedalFine,
        PortamentoTimeFine = ControllerType.PortamentoTimeFine,
        DataEntrySliderFine = ControllerType.DataEntrySliderFine,
        VolumeFine = ControllerType.VolumeFine,
        BalanceFine = ControllerType.BalanceFine,
        PanFine = ControllerType.PanFine,
        ExpressionFine = ControllerType.ExpressionFine,
        EffectControl1Fine = ControllerType.EffectControl1Fine,
        EffectControl2Fine = ControllerType.EffectControl2Fine,
        HoldPedal1 = ControllerType.HoldPedal1,
        Portamento = ControllerType.Portamento,
        SustenutoPedal = ControllerType.SustenutoPedal,
        SoftPedal = ControllerType.SoftPedal,
        LegatoPedal = ControllerType.LegatoPedal,
        HoldPedal2 = ControllerType.HoldPedal2,
        SoundVariation = ControllerType.SoundVariation,
        SoundTimbre = ControllerType.SoundTimbre,
        SoundReleaseTime = ControllerType.SoundReleaseTime,
        SoundAttackTime = ControllerType.SoundAttackTime,
        SoundBrightness = ControllerType.SoundBrightness,
        SoundControl6 = ControllerType.SoundControl6,
        SoundControl7 = ControllerType.SoundControl7,
        SoundControl8 = ControllerType.SoundControl8,
        SoundControl9 = ControllerType.SoundControl9,
        SoundControl10 = ControllerType.SoundControl10,
        GeneralPurposeButton1 = ControllerType.GeneralPurposeButton1,
        GeneralPurposeButton2 = ControllerType.GeneralPurposeButton2,
        GeneralPurposeButton3 = ControllerType.GeneralPurposeButton3,
        GeneralPurposeButton4 = ControllerType.GeneralPurposeButton4,
        EffectsLevel = ControllerType.EffectsLevel,
        TremoloLevel = ControllerType.TremoloLevel,
        ChorusLevel = ControllerType.ChorusLevel,
        CelesteLevel = ControllerType.CelesteLevel,
        PhaserLevel = ControllerType.PhaserLevel,
        DataButtonIncrement = ControllerType.DataButtonIncrement,
        DataButtonDecrement = ControllerType.DataButtonDecrement,
        NonRegisteredParameterFine = ControllerType.NonRegisteredParameterFine,
        NonRegisteredParameterCoarse = ControllerType.NonRegisteredParameterCoarse,
        RegisteredParameterFine = ControllerType.RegisteredParameterFine,
        RegisteredParameterCoarse = ControllerType.RegisteredParameterCoarse,
        AllSoundOff = ControllerType.AllSoundOff,
        AllControllersOff = ControllerType.AllControllersOff,
        LocalKeyboard = ControllerType.LocalKeyboard,
        AllNotesOff = ControllerType.AllNotesOff,
        OmniModeOff = ControllerType.OmniModeOff,
        OmniModeOn = ControllerType.OmniModeOn,
        MonoOperation = ControllerType.MonoOperation,
        PolyOperation = ControllerType.PolyOperation
    }
}
